// Sample email HTML for the prototype
// This email was generated by Alia AI for Salomon XT-6 GORE-TEX product launch

export const SAMPLE_EMAIL = `<html><head></head><body style="background-color:#ffffff;margin:0;padding:0;font-family:'Inter', Helvetica, Arial, sans-serif">
    <div style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0" data-skip-in-text="true">
      The iconic XT-6, now with GORE-TEX waterproof protection. Born in the
      mountains, engineered for the city. Conquer every forecast.
      <div>
        &nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿&nbsp;‌​‍‎‏﻿
      </div>
    </div>
    <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;margin:0 auto;background-color:#ffffff">
      <tbody><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:28px;padding-bottom:20px;padding-left:40px;padding-right:40px;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center" style="padding-bottom:16px">
                            <a href="https://salomon.com" style="color:#067df7;text-decoration-line:none" target="_blank">
                              <img alt="Salomon logo featuring the iconic S mark in black on a white background" height="auto" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/logos/favicon_logo_43ssav.png" style="display:block;outline:none;border:none;text-decoration:none;margin:0 auto;width:48px;height:auto" width="48">
                            </a>
                          </td>
                        </tr>
                        <tr>
                          <td align="center">
                            <table cellpadding="0" cellspacing="0" role="presentation" align="center">
                              <tbody>
                                <tr>
                                  <td class="nav-link" style="padding:0 20px 0 0">
                                    <a href="https://salomon.com/en-us/c/new/inspiration/new-arrivals" style="color:#5a5a5a;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:1.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      New Arrivals
                                    </a>
                                  </td>
                                  <td class="nav-link" style="padding:0 20px 0 0">
                                    <a href="https://salomon.com/en-us/c/collection/bestsellers" style="color:#5a5a5a;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:1.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Best Sellers
                                    </a>
                                  </td>
                                  <td class="nav-link" style="padding:0 20px 0 0">
                                    <a href="https://salomon.com/en-us/sports/trail-running" style="color:#5a5a5a;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:1.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Trail Running
                                    </a>
                                  </td>
                                  <td class="nav-link" style="padding:0">
                                    <a href="https://salomon.com/en-us/sports/hiking" style="color:#5a5a5a;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:1.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Hiking
                                    </a>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;background-color:#ffffff;padding:0">
              <tbody>
                <tr>
                  <td>
                    <img class="mobile-image" alt="Salomon XT-6 GORE-TEX sneaker in a dark grey and black colorway, photographed at a dramatic three-quarter angle on a wet concrete surface reflecting city lights, with rain droplets visible on the GORE-TEX upper, mountain silhouettes faintly visible in the moody atmospheric background" height="500" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/images/gen-gemini-premium-hero-shot-salomon-xt-6-gore-tex-sneak-139071.png" style="display:block;outline:none;border:none;text-decoration:none;width:100%;height:auto;max-width:600px" width="600">
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:40px;padding-bottom:48px;padding-left:40px;padding-right:40px;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center">
                            <p style="font-size:11px;line-height:24px;font-weight:700;color:#5a5a5a;letter-spacing:3px;margin:0 0 12px 0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:12px;margin-left:0">
                              ICONS COLLECTION
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center">
                            <h1 class="hero-heading" style="font-size:42px;font-weight:700;color:#000000;line-height:46px;margin:0 0 16px 0;text-align:center;letter-spacing:-1px;font-family:'Inter', Helvetica, Arial, sans-serif">
                              XT-6 GORE-TEX
                            </h1>
                          </td>
                        </tr>
                        <tr>
                          <td align="center">
                            <p style="font-size:16px;line-height:26px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;max-width:460px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              Born in the mountains. Engineered for the city.
                              The icon that conquered alpine trails now shields
                              you from every urban forecast.
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-top:8px">
                            <p class="price-tag" style="font-size:32px;line-height:24px;font-weight:700;color:#000000;margin:0;text-align:center;letter-spacing:-0.5px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              200,00 EUR
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-top:28px">
                            <a href="https://www.salomon.com/fr-fr/product/xt-6-gore-tex-lg9333/L47861500" class="mobile-button" style="line-height:100%;text-decoration:none;display:inline-block;max-width:100%;mso-padding-alt:0px;background-color:#000000;color:#ffffff;font-size:13px;font-weight:700;padding:16px 48px;border-radius:0px;border:none;letter-spacing:2px;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;padding-top:16px;padding-right:48px;padding-bottom:16px;padding-left:48px" target="_blank">
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:480%;mso-text-raise:24"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;&#8202;&#8202;
                                  </i>
                                <![endif]-->
                              </span>
                              <span style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:12px">
                                EXPLORE NOW
                              </span>
                              <span>
                                <!--[if mso]>
                                  <i style="mso-font-width:480%" hidden>
                                    &#8202;&#8202;&#8202;&#8202;&#8202;&#8203;
                                  </i>
                                <![endif]-->
                              </span>
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding:0;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <img class="mobile-image" alt="Extreme close-up macro photograph of the Salomon XT-6 GORE-TEX upper material showing the tightly woven ripstop fabric with visible GORE-TEX membrane layering, water beads rolling off the surface catching studio light, with the embossed Salomon branding visible in sharp focus against a dark blurred background" height="360" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/images/gen-gemini-extreme-macro-close-up-salomon-xt-6-gore-tex-137935.png" style="display:block;outline:none;border:none;text-decoration:none;width:100%;height:auto;max-width:600px" width="600">
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:56px;padding-bottom:56px;padding-left:60px;padding-right:60px;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center">
                            <p style="font-size:18px;line-height:30px;font-weight:400;color:#1a1a1a;margin:0;text-align:center;font-style:italic;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              From Alpine summits to city streets, the XT-6
                              GORE-TEX carries decades of trail innovation into
                              your everyday. No compromise. No conditions.
                            </p>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:56px;padding-bottom:56px;padding-left:40px;padding-right:40px;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center" style="padding-bottom:40px">
                            <p style="font-size:11px;line-height:24px;font-weight:700;color:#5a5a5a;letter-spacing:3px;margin:0 0 12px 0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:12px;margin-left:0">
                              ENGINEERED FOR EVERYTHING
                            </p>
                            <h2 style="font-size:28px;font-weight:700;color:#000000;line-height:34px;margin:8px 0 0 0;text-align:center;letter-spacing:-0.5px;font-family:'Inter', Helvetica, Arial, sans-serif">
                              Built to Outperform
                            </h2>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td class="feature-cell" width="50%" valign="top" style="padding:0 12px 32px 0">
                            <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#f8f9fa;border-radius:0px;width:100%">
                              <tbody>
                                <tr>
                                  <td style="padding:28px 24px">
                                    <img alt="Shield check icon representing GORE-TEX waterproof protection" height="auto" src="https://cdn.migma.ai/icons/lu/LuShieldCheck/000000.png" style="display:block;outline:none;border:none;text-decoration:none;width:auto;height:28px;margin-bottom:16px" width="28">
                                    <p style="font-size:14px;line-height:24px;font-weight:700;color:#000000;margin:0 0 8px 0;letter-spacing:1px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:8px;margin-left:0">
                                      GORE-TEX Waterproof
                                    </p>
                                    <p style="font-size:13px;line-height:20px;font-weight:400;color:#5a5a5a;margin:0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                      A sealed membrane keeps every drop out
                                      while letting moisture escape. Stay dry
                                      from puddles to downpours.
                                    </p>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                          <td class="feature-cell" width="50%" valign="top" style="padding:0 0 32px 12px">
                            <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#f8f9fa;border-radius:0px;width:100%">
                              <tbody>
                                <tr>
                                  <td style="padding:28px 24px">
                                    <img alt="Lightning bolt icon representing the Quicklace speed lacing system" height="auto" src="https://cdn.migma.ai/icons/lu/LuZap/000000.png" style="display:block;outline:none;border:none;text-decoration:none;width:auto;height:28px;margin-bottom:16px" width="28">
                                    <p style="font-size:14px;line-height:24px;font-weight:700;color:#000000;margin:0 0 8px 0;letter-spacing:1px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:8px;margin-left:0">
                                      Quicklace System
                                    </p>
                                    <p style="font-size:13px;line-height:20px;font-weight:400;color:#5a5a5a;margin:0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                      One pull. Locked in. The single-pull
                                      lacing system delivers a secure,
                                      glove-like fit in seconds.
                                    </p>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td class="feature-cell" width="50%" valign="top" style="padding:0 12px 0 0">
                            <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#f8f9fa;border-radius:0px;width:100%">
                              <tbody>
                                <tr>
                                  <td style="padding:28px 24px">
                                    <img alt="Mountain and sun icon representing Contagrip all-terrain outsole" height="auto" src="https://cdn.migma.ai/icons/fa6/FaMountainSun/000000.png" style="display:block;outline:none;border:none;text-decoration:none;width:auto;height:28px;margin-bottom:16px" width="28">
                                    <p style="font-size:14px;line-height:24px;font-weight:700;color:#000000;margin:0 0 8px 0;letter-spacing:1px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:8px;margin-left:0">
                                      Contagrip Outsole
                                    </p>
                                    <p style="font-size:13px;line-height:20px;font-weight:400;color:#5a5a5a;margin:0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                      Engineered grip for wet pavement, gravel,
                                      and trail. Every surface is your surface.
                                    </p>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                          <td class="feature-cell" width="50%" valign="top" style="padding:0 0 0 12px">
                            <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#f8f9fa;border-radius:0px;width:100%">
                              <tbody>
                                <tr>
                                  <td style="padding:28px 24px">
                                    <img alt="Layers icon representing advanced chassis midsole technology" height="auto" src="https://cdn.migma.ai/icons/lu/LuLayers/000000.png" style="display:block;outline:none;border:none;text-decoration:none;width:auto;height:28px;margin-bottom:16px" width="28">
                                    <p style="font-size:14px;line-height:24px;font-weight:700;color:#000000;margin:0 0 8px 0;letter-spacing:1px;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:8px;margin-left:0">
                                      Advanced Chassis
                                    </p>
                                    <p style="font-size:13px;line-height:20px;font-weight:400;color:#5a5a5a;margin:0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                      A dual-density midsole with a protective
                                      chassis absorbs impact and stabilizes
                                      every stride.
                                    </p>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding:0;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation" dir="ltr">
                      <tbody>
                        <tr>
                          <td class="stack-column zigzag-image-cell" width="50%" valign="middle" style="padding:0">
                            <img class="mobile-image" alt="Athletic person wearing Salomon XT-6 GORE-TEX shoes walking confidently through rain-soaked city streets at dusk, reflections of warm streetlights on wet cobblestones, wearing dark minimalist technical outerwear, urban architecture with a hint of distant mountains visible in the twilight skyline" height="380" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/images/gen-gemini-lifestyle-photography-athletic-person-wearing-137384.png" style="display:block;outline:none;border:none;text-decoration:none;width:100%;height:auto;max-width:300px" width="300">
                          </td>
                          <td class="stack-column zigzag-text-cell" width="50%" valign="middle" style="padding:0 40px">
                            <p style="font-size:11px;line-height:24px;font-weight:700;color:#5a5a5a;letter-spacing:3px;margin:0 0 12px 0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:12px;margin-left:0">
                              TRAIL TO STREET
                            </p>
                            <h2 style="font-size:24px;font-weight:700;color:#000000;line-height:30px;margin:8px 0 12px 0;letter-spacing:-0.5px;font-family:'Inter', Helvetica, Arial, sans-serif">
                              Heritage Reinvented
                            </h2>
                            <p style="font-size:14px;line-height:22px;font-weight:400;color:#5a5a5a;margin:0 0 24px 0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:24px;margin-left:0">
                              The XT-6 silhouette earned its legend on the
                              world's toughest trails. Now, GORE-TEX technology
                              transforms it into your ultimate city companion —
                              ready for commutes, cobblestones, and cloudburst
                              alike.
                            </p>
                            <a href="https://www.salomon.com/fr-fr/product/xt-6-gore-tex-lg9333/L47861500" class="mobile-button" style="line-height:100%;text-decoration:none;display:inline-block;max-width:100%;mso-padding-alt:0px;background-color:#ffffff;color:#000000;font-size:12px;font-weight:700;padding:12px 28px;border-radius:0px;border:2px solid #000000;letter-spacing:2px;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;padding-top:12px;padding-right:28px;padding-bottom:12px;padding-left:28px" target="_blank">
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:466.6666666666667%;mso-text-raise:18"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;
                                  </i>
                                <![endif]-->
                              </span>
                              <span style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:9px">
                                DISCOVER MORE
                              </span>
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:466.6666666666667%"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;&#8203;
                                  </i>
                                <![endif]-->
                              </span>
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding:0;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation" dir="rtl">
                      <tbody>
                        <tr>
                          <td class="stack-column zigzag-image-cell" dir="ltr" width="50%" valign="middle" style="padding:0">
                            <img class="mobile-image" alt="Close-up bottom view of the Salomon XT-6 GORE-TEX Contagrip outsole showing deep multi-directional lugs and aggressive tread pattern in charcoal grey rubber, with textured wet concrete beneath showing grip marks, studio-quality side lighting emphasizing the engineered sole geometry and Contagrip branding" height="380" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/images/gen-gemini-technical-studio-shot-salomon-xt-6-contagrip-139600.png" style="display:block;outline:none;border:none;text-decoration:none;width:100%;height:auto;max-width:300px" width="300">
                          </td>
                          <td class="stack-column zigzag-text-cell" dir="ltr" width="50%" valign="middle" style="padding:0 40px">
                            <p style="font-size:11px;line-height:24px;font-weight:700;color:#5a5a5a;letter-spacing:3px;margin:0 0 12px 0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:12px;margin-left:0">
                              ALL-TERRAIN CONFIDENCE
                            </p>
                            <h2 style="font-size:24px;font-weight:700;color:#000000;line-height:30px;margin:8px 0 12px 0;letter-spacing:-0.5px;font-family:'Inter', Helvetica, Arial, sans-serif">
                              Grip That Conquers
                            </h2>
                            <p style="font-size:14px;line-height:22px;font-weight:400;color:#5a5a5a;margin:0 0 24px 0;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-right:0;margin-bottom:24px;margin-left:0">
                              Contagrip outsole technology delivers unwavering
                              traction across wet marble, loose gravel, and
                              slick subway stairs. Wherever you step, you lead.
                            </p>
                            <a href="https://www.salomon.com/fr-fr/product/xt-6-gore-tex-lg9333/L47861500" class="mobile-button" style="line-height:100%;text-decoration:none;display:inline-block;max-width:100%;mso-padding-alt:0px;background-color:#ffffff;color:#000000;font-size:12px;font-weight:700;padding:12px 28px;border-radius:0px;border:2px solid #000000;letter-spacing:2px;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;padding-top:12px;padding-right:28px;padding-bottom:12px;padding-left:28px" target="_blank">
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:466.6666666666667%;mso-text-raise:18"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;
                                  </i>
                                <![endif]-->
                              </span>
                              <span style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:9px">
                                SEE THE TECH
                              </span>
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:466.6666666666667%"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;&#8203;
                                  </i>
                                <![endif]-->
                              </span>
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:56px;padding-bottom:56px;padding-left:40px;padding-right:40px;background-color:#ffffff">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center">
                            <img class="mobile-image" alt="Salomon XT-6 GORE-TEX pair arranged in a dynamic composition on a clean white surface, one shoe standing upright showing the lateral profile with visible GORE-TEX branding and Quicklace toggle, the other shoe on its side revealing the Contagrip outsole pattern, soft overhead studio lighting casting subtle shadows" height="300" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/images/gen-gemini-dynamic-studio-composition-pair-salomon-xt-6-138976.png" style="display:block;outline:none;border:none;text-decoration:none;width:100%;height:auto;max-width:520px" width="520">
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-top:32px">
                            <h2 style="font-size:26px;font-weight:700;color:#000000;line-height:32px;margin:0 0 12px 0;text-align:center;letter-spacing:-0.5px;font-family:'Inter', Helvetica, Arial, sans-serif">
                              Ready to Conquer Every Forecast?
                            </h2>
                          </td>
                        </tr>
                        <tr>
                          <td align="center">
                            <p style="font-size:15px;line-height:24px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              The XT-6 GORE-TEX is available now. Free shipping
                              for S/PLUS members.
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-top:24px;padding-bottom:8px">
                            <a href="https://www.salomon.com/fr-fr/product/xt-6-gore-tex-lg9333/L47861500" class="mobile-button" style="line-height:100%;text-decoration:none;display:inline-block;max-width:100%;mso-padding-alt:0px;background-color:#000000;color:#ffffff;font-size:13px;font-weight:700;padding:16px 48px;border-radius:0px;border:none;letter-spacing:2px;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;padding-top:16px;padding-right:48px;padding-bottom:16px;padding-left:48px" target="_blank">
                              <span>
                                <!--[if mso]>
                                  <i
                                    style="mso-font-width:480%;mso-text-raise:24"
                                    hidden
                                  >
                                    &#8202;&#8202;&#8202;&#8202;&#8202;
                                  </i>
                                <![endif]-->
                              </span>
                              <span style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:12px">
                                SHOP XT-6 GORE-TEX
                              </span>
                              <span>
                                <!--[if mso]>
                                  <i style="mso-font-width:480%" hidden>
                                    &#8202;&#8202;&#8202;&#8202;&#8202;&#8203;
                                  </i>
                                <![endif]-->
                              </span>
                            </a>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-top:12px">
                            <a href="https://www.salomon.com/en-us/store-finder" style="color:#1a1a1a;text-decoration-line:none;font-size:13px;font-weight:400;text-decoration:underline;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                              Find a store near you
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr><tr style="width:100%"><td><table align="center" width="100%" class="content-padding" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width:600px;padding-top:40px;padding-bottom:40px;padding-left:40px;padding-right:40px;background-color:#f8f9fa">
              <tbody>
                <tr>
                  <td>
                    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                      <tbody>
                        <tr>
                          <td align="center" style="padding-bottom:20px">
                            <img alt="Salomon logo in black" height="auto" src="https://cdn.migma.ai/projects/69aaf70bfefbb0584d4b8961/logos/favicon_logo_43ssav.png" style="display:block;outline:none;border:none;text-decoration:none;margin:0 auto;width:36px;height:auto" width="36">
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-bottom:20px">
                            <table cellpadding="0" cellspacing="0" role="presentation" align="center">
                              <tbody>
                                <tr>
                                  <td style="padding-right:16px">
                                    <a href="https://www.instagram.com/salomon/" style="color:#067df7;text-decoration-line:none" target="_blank">
                                      <img src="https://cdn.migma.ai/icons/fa/FaInstagram/1a1a1a.png" alt="Instagram" width="24" height="auto" style="display:inline-block;outline:none;border:none;text-decoration:none;height:24px;width:auto" loading="lazy">
                                    </a>
                                  </td>
                                  <td style="padding-right:16px">
                                    <a href="https://www.facebook.com/salomon/" style="color:#067df7;text-decoration-line:none" target="_blank">
                                      <img src="https://cdn.migma.ai/icons/fa6/FaFacebook/1a1a1a.png" alt="Facebook" width="24" height="auto" style="display:inline-block;outline:none;border:none;text-decoration:none;height:24px;width:auto" loading="lazy">
                                    </a>
                                  </td>
                                  <td>
                                    <a href="#" style="color:#067df7;text-decoration-line:none" target="_blank">
                                      <img src="https://cdn.migma.ai/icons/fa/FaYoutube/1a1a1a.png" alt="YouTube" width="24" height="auto" style="display:inline-block;outline:none;border:none;text-decoration:none;height:24px;width:auto" loading="lazy">
                                    </a>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-bottom:12px">
                            <table cellpadding="0" cellspacing="0" role="presentation" align="center">
                              <tbody>
                                <tr>
                                  <td style="padding-right:24px">
                                    <a href="https://salomon.com/en-us/c/new/inspiration/new-arrivals" style="color:#536a97;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:0.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      New Arrivals
                                    </a>
                                  </td>
                                  <td style="padding-right:24px">
                                    <a href="https://salomon.com/en-us/c/collection/bestsellers" style="color:#536a97;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:0.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Best Sellers
                                    </a>
                                  </td>
                                  <td style="padding-right:24px">
                                    <a href="https://salomon.com/en-us/lp/g/sustainability" style="color:#536a97;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:0.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Sustainability
                                    </a>
                                  </td>
                                  <td>
                                    <a href="https://www.salomon.com/en-us/store-finder" style="color:#536a97;text-decoration-line:none;font-size:11px;font-weight:400;text-decoration:none;letter-spacing:0.5px;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                      Stores
                                    </a>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-bottom:8px">
                            <p style="font-size:11px;line-height:24px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              2025 Salomon. All Rights Reserved.
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-bottom:8px">
                            <p style="font-size:11px;line-height:24px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              Salomon S.A.S. | Annecy, France
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center" style="padding-bottom:8px">
                            <p style="font-size:11px;line-height:18px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              Free shipping for S/PLUS members. Terms and
                              conditions apply.
                            </p>
                          </td>
                        </tr>
                        <tr>
                          <td align="center">
                            <p style="font-size:11px;line-height:18px;font-weight:400;color:#5a5a5a;margin:0;text-align:center;font-family:'Inter', Helvetica, Arial, sans-serif;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                              This email was sent to you by Salomon. You can
                              <a href="#" style="color:#536a97;text-decoration-line:none;text-decoration:underline;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                unsubscribe
                              </a>
                              or
                              <a href="#" style="color:#536a97;text-decoration-line:none;text-decoration:underline;font-family:'Inter', Helvetica, Arial, sans-serif" target="_blank">
                                manage your preferences
                              </a>
                              at any time.
                            </p>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table></td></tr></tbody>
    </table>
  

</body></html>`;
